<?php
/**
 *  Autoloader function generated by crodas/Autoloader
 *
 *  https://github.com/crodas/Autoloader
 *
 *  This is a generated file, do not modify it.
 */


spl_autoload_register(function ($class) {
    /*
        This array has a map of (class => file)
    */

    // classes {{{
    static $classes = array (
  'haanga2\\extension\\tag\\escape\\escape' => '/Extension/Tags/Escape.php',
  'haanga2\\compiler\\tokenizer' => '/Compiler/Tokenizer.php',
  'haanga2_yytoken' => '/Compiler/Parser.php',
  'haanga2_yystackentry' => '/Compiler/Parser.php',
  'haanga2_compiler_parser' => '/Compiler/Parser.php',
  'haanga2\\cli\\build' => '/Cli/Build.php',
  'haanga2\\cli\\compiler' => '/Cli/Compiler.php',
  'haanga2\\cli' => '/Cli.php',
  'haanga2\\extension' => '/Extension.php',
  'notoj\\notoj' => '/../../vendor/crodas/Notoj/lib/Notoj/Notoj.php',
  'notoj\\file' => '/../../vendor/crodas/Notoj/lib/Notoj/File.php',
  'notoj\\annotation' => '/../../vendor/crodas/Notoj/lib/Notoj/Annotation.php',
  'notoj\\tokenizer' => '/../../vendor/crodas/Notoj/lib/Notoj/Tokenizer.php',
  'notoj_yytoken' => '/../../vendor/crodas/Notoj/lib/Notoj/Parser.php',
  'notoj_yystackentry' => '/../../vendor/crodas/Notoj/lib/Notoj/Parser.php',
  'notoj_parser' => '/../../vendor/crodas/Notoj/lib/Notoj/Parser.php',
  'notoj\\reflectionfunction' => '/../../vendor/crodas/Notoj/lib/Notoj/ReflectionFunction.php',
  'notoj\\reflectionproperty' => '/../../vendor/crodas/Notoj/lib/Notoj/ReflectionProperty.php',
  'notoj\\reflectionmethod' => '/../../vendor/crodas/Notoj/lib/Notoj/ReflectionMethod.php',
  'notoj\\reflectionclass' => '/../../vendor/crodas/Notoj/lib/Notoj/ReflectionClass.php',
  'notoj\\reflectionobject' => '/../../vendor/crodas/Notoj/lib/Notoj/ReflectionObject.php',
  'artifex' => '/../../vendor/crodas/Artifex/lib/Artifex.php',
  'artifex\\runtime\\base' => '/../../vendor/crodas/Artifex/lib/Artifex/Runtime/Base.php',
  'artifex\\runtime\\variable' => '/../../vendor/crodas/Artifex/lib/Artifex/Runtime/Variable.php',
  'artifex\\runtime\\exec' => '/../../vendor/crodas/Artifex/lib/Artifex/Runtime/Exec.php',
  'artifex\\runtime\\term' => '/../../vendor/crodas/Artifex/lib/Artifex/Runtime/Term.php',
  'artifex\\runtime\\rawstring' => '/../../vendor/crodas/Artifex/lib/Artifex/Runtime/RawString.php',
  'artifex\\runtime\\expr' => '/../../vendor/crodas/Artifex/lib/Artifex/Runtime/Expr.php',
  'artifex\\runtime\\deffunction' => '/../../vendor/crodas/Artifex/lib/Artifex/Runtime/DefFunction.php',
  'artifex\\runtime\\concat' => '/../../vendor/crodas/Artifex/lib/Artifex/Runtime/Concat.php',
  'artifex\\runtime\\assign' => '/../../vendor/crodas/Artifex/lib/Artifex/Runtime/Assign.php',
  'artifex\\runtime\\expr_if' => '/../../vendor/crodas/Artifex/lib/Artifex/Runtime/Expr/If.php',
  'artifex\\runtime\\expr_foreach' => '/../../vendor/crodas/Artifex/lib/Artifex/Runtime/Expr/Foreach.php',
  'artifex\\runtime\\whitespace' => '/../../vendor/crodas/Artifex/lib/Artifex/Runtime/Whitespace.php',
  'artifex\\tokenizer' => '/../../vendor/crodas/Artifex/lib/Artifex/Tokenizer.php',
  'artifex_yytoken' => '/../../vendor/crodas/Artifex/lib/Artifex/Parser.php',
  'artifex_yystackentry' => '/../../vendor/crodas/Artifex/lib/Artifex/Parser.php',
  'artifex_parser' => '/../../vendor/crodas/Artifex/lib/Artifex/Parser.php',
  'artifex\\util\\phptokens' => '/../../vendor/crodas/Artifex/lib/Artifex/Util/PHPTokens.php',
  'artifex\\runtime' => '/../../vendor/crodas/Artifex/lib/Artifex/Runtime.php',
);
    // }}}

    // deps {{{
    static $deps    = array (
  'notoj\\file' => 
  array (
    0 => 'notoj\\notoj',
  ),
  'notoj\\tokenizer' => 
  array (
    0 => 'notoj\\notoj',
  ),
  'notoj\\reflectionfunction' => 
  array (
    0 => 'notoj\\notoj',
  ),
  'notoj\\reflectionproperty' => 
  array (
    0 => 'notoj\\notoj',
  ),
  'notoj\\reflectionmethod' => 
  array (
    0 => 'notoj\\notoj',
  ),
  'notoj\\reflectionclass' => 
  array (
    0 => 'notoj\\notoj',
  ),
  'notoj\\reflectionobject' => 
  array (
    0 => 'notoj\\notoj',
  ),
  'artifex\\runtime\\variable' => 
  array (
    0 => 'artifex\\runtime\\base',
  ),
  'artifex\\runtime\\exec' => 
  array (
    0 => 'artifex\\runtime\\base',
  ),
  'artifex\\runtime\\term' => 
  array (
    0 => 'artifex\\runtime\\base',
  ),
  'artifex\\runtime\\rawstring' => 
  array (
    0 => 'artifex\\runtime\\base',
  ),
  'artifex\\runtime\\expr' => 
  array (
    0 => 'artifex\\runtime\\base',
  ),
  'artifex\\runtime\\deffunction' => 
  array (
    0 => 'artifex\\runtime\\base',
  ),
  'artifex\\runtime\\concat' => 
  array (
    0 => 'artifex\\runtime\\base',
  ),
  'artifex\\runtime\\assign' => 
  array (
    0 => 'artifex\\runtime\\base',
  ),
  'artifex\\runtime\\expr_if' => 
  array (
    0 => 'artifex\\runtime\\base',
  ),
  'artifex\\runtime\\expr_foreach' => 
  array (
    0 => 'artifex\\runtime\\base',
  ),
  'artifex\\runtime\\whitespace' => 
  array (
    0 => 'artifex\\runtime\\base',
  ),
);
    // }}}

    $class = strtolower($class);
    if (isset($classes[$class])) {
        if (!empty($deps[$class])) {
            foreach ($deps[$class] as $zclass) {
                if (!class_exists($zclass, false)) {
                    require __DIR__  . $classes[$zclass];
                }
            }
        }

        if (!class_exists($class, false)) {
            require __DIR__  . $classes[$class];
        }
        return true;
    }

    return false;
});


